# OpenSearch image runs as UID/GID 1000 (opensearch user)
# Does not fit restricted SCC/namespace UID range
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: opensearch-1000
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
runAsUser:
  type: RunAsAny
runAsGroup:
  type: RunAsAny
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 1000
supplementalGroups:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - runtime/default
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:demo:opensearch-sa
