apiVersion: route.openshift.io/v1
kind: Route
metaData:
  name: rag-route
spec:
  to:
    kind: Service
    name: rag-service
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPoicy: Redirect